---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: success
  run_list: 
    - recipe[simplelog_handler]
    - recipe[dummy_cookbook::success]
  attributes: {}
- name: fail
  run_list: 
    - recipe[simplelog_handler]
    - recipe[dummy_cookbook::fail]
  attributes: {}
